package com.sharesmile.share;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ACHIEVED_BADGE".
 */
public class AchievedBadge {

    private Long id;
    private Integer userId;
    private Integer badgeId;
    private String causeId;
    private String category;
    private String categoryStatus;
    private String paramDone;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AchievedBadge() {
    }

    public AchievedBadge(Long id) {
        this.id = id;
    }

    public AchievedBadge(Long id, Integer userId, Integer badgeId, String causeId, String category, String categoryStatus, String paramDone) {
        this.id = id;
        this.userId = userId;
        this.badgeId = badgeId;
        this.causeId = causeId;
        this.category = category;
        this.categoryStatus = categoryStatus;
        this.paramDone = paramDone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getBadgeId() {
        return badgeId;
    }

    public void setBadgeId(Integer badgeId) {
        this.badgeId = badgeId;
    }

    public String getCauseId() {
        return causeId;
    }

    public void setCauseId(String causeId) {
        this.causeId = causeId;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getCategoryStatus() {
        return categoryStatus;
    }

    public void setCategoryStatus(String categoryStatus) {
        this.categoryStatus = categoryStatus;
    }

    public String getParamDone() {
        return paramDone;
    }

    public void setParamDone(String paramDone) {
        this.paramDone = paramDone;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
