package com.sharesmile.share;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ACHIEVED_BADGE".
 */
public class AchievedBadge {

    private Long id;
    private int userId;
    private int badgeIdInProgress;
    private int badgeIdAchieved;
    /** Not-null value. */
    private String badgeType;
    private String causeIdJson;
    /** Not-null value. */
    private String category;
    /** Not-null value. */
    private String categoryStatus;
    private double paramDone;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AchievedBadge() {
    }

    public AchievedBadge(Long id) {
        this.id = id;
    }

    public AchievedBadge(Long id, int userId, int badgeIdInProgress, int badgeIdAchieved, String badgeType, String causeIdJson, String category, String categoryStatus, double paramDone) {
        this.id = id;
        this.userId = userId;
        this.badgeIdInProgress = badgeIdInProgress;
        this.badgeIdAchieved = badgeIdAchieved;
        this.badgeType = badgeType;
        this.causeIdJson = causeIdJson;
        this.category = category;
        this.categoryStatus = categoryStatus;
        this.paramDone = paramDone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getBadgeIdInProgress() {
        return badgeIdInProgress;
    }

    public void setBadgeIdInProgress(int badgeIdInProgress) {
        this.badgeIdInProgress = badgeIdInProgress;
    }

    public int getBadgeIdAchieved() {
        return badgeIdAchieved;
    }

    public void setBadgeIdAchieved(int badgeIdAchieved) {
        this.badgeIdAchieved = badgeIdAchieved;
    }

    /** Not-null value. */
    public String getBadgeType() {
        return badgeType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBadgeType(String badgeType) {
        this.badgeType = badgeType;
    }

    public String getCauseIdJson() {
        return causeIdJson;
    }

    public void setCauseIdJson(String causeIdJson) {
        this.causeIdJson = causeIdJson;
    }

    /** Not-null value. */
    public String getCategory() {
        return category;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory(String category) {
        this.category = category;
    }

    /** Not-null value. */
    public String getCategoryStatus() {
        return categoryStatus;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategoryStatus(String categoryStatus) {
        this.categoryStatus = categoryStatus;
    }

    public double getParamDone() {
        return paramDone;
    }

    public void setParamDone(double paramDone) {
        this.paramDone = paramDone;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
