package com.sharesmile.share;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ACHIEVED_TITLE".
 */
public class AchievedTitle {

    private Long id;
    private int titleId;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String categoryName;
    private int userId;
    private boolean isSync;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AchievedTitle() {
    }

    public AchievedTitle(Long id) {
        this.id = id;
    }

    public AchievedTitle(Long id, int titleId, String title, String categoryName, int userId, boolean isSync) {
        this.id = id;
        this.titleId = titleId;
        this.title = title;
        this.categoryName = categoryName;
        this.userId = userId;
        this.isSync = isSync;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getTitleId() {
        return titleId;
    }

    public void setTitleId(int titleId) {
        this.titleId = titleId;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getCategoryName() {
        return categoryName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public boolean getIsSync() {
        return isSync;
    }

    public void setIsSync(boolean isSync) {
        this.isSync = isSync;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return title;
    }

    // KEEP METHODS END
}
