package com.sharesmile.share;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ACHIEVED_TITLE".
 */
public class AchievedTitle {

    private Long id;
    private long serverId;
    private int titleId;
    /** Not-null value. */
    private String title;
    private long categoryId;
    /** Not-null value. */
    private String categoryName;
    /** Not-null value. */
    private java.util.Date achievedTime;
    /** Not-null value. */
    private String badgeType;
    private long userId;
    private boolean isSync;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AchievedTitle() {
    }

    public AchievedTitle(Long id) {
        this.id = id;
    }

    public AchievedTitle(Long id, long serverId, int titleId, String title, long categoryId, String categoryName, java.util.Date achievedTime, String badgeType, long userId, boolean isSync) {
        this.id = id;
        this.serverId = serverId;
        this.titleId = titleId;
        this.title = title;
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.achievedTime = achievedTime;
        this.badgeType = badgeType;
        this.userId = userId;
        this.isSync = isSync;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getServerId() {
        return serverId;
    }

    public void setServerId(long serverId) {
        this.serverId = serverId;
    }

    public int getTitleId() {
        return titleId;
    }

    public void setTitleId(int titleId) {
        this.titleId = titleId;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }

    /** Not-null value. */
    public String getCategoryName() {
        return categoryName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /** Not-null value. */
    public java.util.Date getAchievedTime() {
        return achievedTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAchievedTime(java.util.Date achievedTime) {
        this.achievedTime = achievedTime;
    }

    /** Not-null value. */
    public String getBadgeType() {
        return badgeType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBadgeType(String badgeType) {
        this.badgeType = badgeType;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public boolean getIsSync() {
        return isSync;
    }

    public void setIsSync(boolean isSync) {
        this.isSync = isSync;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return title;
    }
    // KEEP METHODS END

}
