package com.sharesmile.share;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.sharesmile.share.AchievedBadge;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACHIEVED_BADGE".
*/
public class AchievedBadgeDao extends AbstractDao<AchievedBadge, Long> {

    public static final String TABLENAME = "ACHIEVED_BADGE";

    /**
     * Properties of entity AchievedBadge.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, int.class, "userId", false, "USER_ID");
        public final static Property BadgeIdInProgress = new Property(2, int.class, "badgeIdInProgress", false, "BADGE_ID_IN_PROGRESS");
        public final static Property BadgeIdAchieved = new Property(3, int.class, "badgeIdAchieved", false, "BADGE_ID_ACHIEVED");
        public final static Property BadgeType = new Property(4, String.class, "badgeType", false, "BADGE_TYPE");
        public final static Property CauseIdJson = new Property(5, String.class, "causeIdJson", false, "CAUSE_ID_JSON");
        public final static Property Category = new Property(6, String.class, "category", false, "CATEGORY");
        public final static Property CategoryStatus = new Property(7, String.class, "categoryStatus", false, "CATEGORY_STATUS");
        public final static Property ParamDone = new Property(8, double.class, "paramDone", false, "PARAM_DONE");
    };


    public AchievedBadgeDao(DaoConfig config) {
        super(config);
    }
    
    public AchievedBadgeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACHIEVED_BADGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"BADGE_ID_IN_PROGRESS\" INTEGER NOT NULL ," + // 2: badgeIdInProgress
                "\"BADGE_ID_ACHIEVED\" INTEGER NOT NULL ," + // 3: badgeIdAchieved
                "\"BADGE_TYPE\" TEXT NOT NULL ," + // 4: badgeType
                "\"CAUSE_ID_JSON\" TEXT," + // 5: causeIdJson
                "\"CATEGORY\" TEXT NOT NULL ," + // 6: category
                "\"CATEGORY_STATUS\" TEXT NOT NULL ," + // 7: categoryStatus
                "\"PARAM_DONE\" REAL NOT NULL );"); // 8: paramDone
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACHIEVED_BADGE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AchievedBadge entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getBadgeIdInProgress());
        stmt.bindLong(4, entity.getBadgeIdAchieved());
        stmt.bindString(5, entity.getBadgeType());
 
        String causeIdJson = entity.getCauseIdJson();
        if (causeIdJson != null) {
            stmt.bindString(6, causeIdJson);
        }
        stmt.bindString(7, entity.getCategory());
        stmt.bindString(8, entity.getCategoryStatus());
        stmt.bindDouble(9, entity.getParamDone());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AchievedBadge readEntity(Cursor cursor, int offset) {
        AchievedBadge entity = new AchievedBadge( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // userId
            cursor.getInt(offset + 2), // badgeIdInProgress
            cursor.getInt(offset + 3), // badgeIdAchieved
            cursor.getString(offset + 4), // badgeType
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // causeIdJson
            cursor.getString(offset + 6), // category
            cursor.getString(offset + 7), // categoryStatus
            cursor.getDouble(offset + 8) // paramDone
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AchievedBadge entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getInt(offset + 1));
        entity.setBadgeIdInProgress(cursor.getInt(offset + 2));
        entity.setBadgeIdAchieved(cursor.getInt(offset + 3));
        entity.setBadgeType(cursor.getString(offset + 4));
        entity.setCauseIdJson(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCategory(cursor.getString(offset + 6));
        entity.setCategoryStatus(cursor.getString(offset + 7));
        entity.setParamDone(cursor.getDouble(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AchievedBadge entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AchievedBadge entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
