package com.sharesmile.share;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BADGE".
 */
public class Badge {

    private Long id;
    private Integer badgeId;
    private String type;
    private String category;
    private String name;
    private Integer noOfStars;
    private String imageUrl;
    private String description1;
    private String description2;
    private String description3;
    private String badgeParameter;
    private String badgeParameterCheck;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Badge() {
    }

    public Badge(Long id) {
        this.id = id;
    }

    public Badge(Long id, Integer badgeId, String type, String category, String name, Integer noOfStars, String imageUrl, String description1, String description2, String description3, String badgeParameter, String badgeParameterCheck) {
        this.id = id;
        this.badgeId = badgeId;
        this.type = type;
        this.category = category;
        this.name = name;
        this.noOfStars = noOfStars;
        this.imageUrl = imageUrl;
        this.description1 = description1;
        this.description2 = description2;
        this.description3 = description3;
        this.badgeParameter = badgeParameter;
        this.badgeParameterCheck = badgeParameterCheck;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getBadgeId() {
        return badgeId;
    }

    public void setBadgeId(Integer badgeId) {
        this.badgeId = badgeId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getNoOfStars() {
        return noOfStars;
    }

    public void setNoOfStars(Integer noOfStars) {
        this.noOfStars = noOfStars;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getDescription1() {
        return description1;
    }

    public void setDescription1(String description1) {
        this.description1 = description1;
    }

    public String getDescription2() {
        return description2;
    }

    public void setDescription2(String description2) {
        this.description2 = description2;
    }

    public String getDescription3() {
        return description3;
    }

    public void setDescription3(String description3) {
        this.description3 = description3;
    }

    public String getBadgeParameter() {
        return badgeParameter;
    }

    public void setBadgeParameter(String badgeParameter) {
        this.badgeParameter = badgeParameter;
    }

    public String getBadgeParameterCheck() {
        return badgeParameterCheck;
    }

    public void setBadgeParameterCheck(String badgeParameterCheck) {
        this.badgeParameterCheck = badgeParameterCheck;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
