package com.sharesmile.share;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BADGE".
 */
public class Badge {

    private Long id;
    private int badgeId;
    /** Not-null value. */
    private String type;
    /** Not-null value. */
    private String category;
    /** Not-null value. */
    private String name;
    private int noOfStars;
    private String imageUrl;
    /** Not-null value. */
    private String description1;
    private String description2;
    private String description3;
    private String description_inprogress;
    private String share_badge_content;
    private double badgeParameter;
    private String badgeParameterCheck;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Badge() {
    }

    public Badge(Long id) {
        this.id = id;
    }

    public Badge(Long id, int badgeId, String type, String category, String name, int noOfStars, String imageUrl, String description1, String description2, String description3, String description_inprogress, String share_badge_content, double badgeParameter, String badgeParameterCheck) {
        this.id = id;
        this.badgeId = badgeId;
        this.type = type;
        this.category = category;
        this.name = name;
        this.noOfStars = noOfStars;
        this.imageUrl = imageUrl;
        this.description1 = description1;
        this.description2 = description2;
        this.description3 = description3;
        this.description_inprogress = description_inprogress;
        this.share_badge_content = share_badge_content;
        this.badgeParameter = badgeParameter;
        this.badgeParameterCheck = badgeParameterCheck;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getBadgeId() {
        return badgeId;
    }

    public void setBadgeId(int badgeId) {
        this.badgeId = badgeId;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getCategory() {
        return category;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory(String category) {
        this.category = category;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getNoOfStars() {
        return noOfStars;
    }

    public void setNoOfStars(int noOfStars) {
        this.noOfStars = noOfStars;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /** Not-null value. */
    public String getDescription1() {
        return description1;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescription1(String description1) {
        this.description1 = description1;
    }

    public String getDescription2() {
        return description2;
    }

    public void setDescription2(String description2) {
        this.description2 = description2;
    }

    public String getDescription3() {
        return description3;
    }

    public void setDescription3(String description3) {
        this.description3 = description3;
    }

    public String getDescription_inprogress() {
        return description_inprogress;
    }

    public void setDescription_inprogress(String description_inprogress) {
        this.description_inprogress = description_inprogress;
    }

    public String getShare_badge_content() {
        return share_badge_content;
    }

    public void setShare_badge_content(String share_badge_content) {
        this.share_badge_content = share_badge_content;
    }

    public double getBadgeParameter() {
        return badgeParameter;
    }

    public void setBadgeParameter(double badgeParameter) {
        this.badgeParameter = badgeParameter;
    }

    public String getBadgeParameterCheck() {
        return badgeParameterCheck;
    }

    public void setBadgeParameterCheck(String badgeParameterCheck) {
        this.badgeParameterCheck = badgeParameterCheck;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
