package com.sharesmile.share;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig workoutDaoConfig;
    private final DaoConfig userDaoConfig;

    private final WorkoutDao workoutDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        workoutDaoConfig = daoConfigMap.get(WorkoutDao.class).clone();
        workoutDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        workoutDao = new WorkoutDao(workoutDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Workout.class, workoutDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        workoutDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public WorkoutDao getWorkoutDao() {
        return workoutDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
