package com.sharesmile.share;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TITLE".
 */
public class Title {

    private Long id;
    private int titleId;
    /** Not-null value. */
    private String title;
    private int categoryId;
    /** Not-null value. */
    private String category;
    private int goalNStars;
    private String imageUrl;
    /** Not-null value. */
    private String winningMessage;
    private String description_1;
    private String description_2;
    private String description_3;
    private String share_message;
    /** Not-null value. */
    private String badgeType;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Title() {
    }

    public Title(Long id) {
        this.id = id;
    }

    public Title(Long id, int titleId, String title, int categoryId, String category, int goalNStars, String imageUrl, String winningMessage, String description_1, String description_2, String description_3, String share_message, String badgeType) {
        this.id = id;
        this.titleId = titleId;
        this.title = title;
        this.categoryId = categoryId;
        this.category = category;
        this.goalNStars = goalNStars;
        this.imageUrl = imageUrl;
        this.winningMessage = winningMessage;
        this.description_1 = description_1;
        this.description_2 = description_2;
        this.description_3 = description_3;
        this.share_message = share_message;
        this.badgeType = badgeType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getTitleId() {
        return titleId;
    }

    public void setTitleId(int titleId) {
        this.titleId = titleId;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public int getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    /** Not-null value. */
    public String getCategory() {
        return category;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory(String category) {
        this.category = category;
    }

    public int getGoalNStars() {
        return goalNStars;
    }

    public void setGoalNStars(int goalNStars) {
        this.goalNStars = goalNStars;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /** Not-null value. */
    public String getWinningMessage() {
        return winningMessage;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWinningMessage(String winningMessage) {
        this.winningMessage = winningMessage;
    }

    public String getDescription_1() {
        return description_1;
    }

    public void setDescription_1(String description_1) {
        this.description_1 = description_1;
    }

    public String getDescription_2() {
        return description_2;
    }

    public void setDescription_2(String description_2) {
        this.description_2 = description_2;
    }

    public String getDescription_3() {
        return description_3;
    }

    public void setDescription_3(String description_3) {
        this.description_3 = description_3;
    }

    public String getShare_message() {
        return share_message;
    }

    public void setShare_message(String share_message) {
        this.share_message = share_message;
    }

    /** Not-null value. */
    public String getBadgeType() {
        return badgeType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBadgeType(String badgeType) {
        this.badgeType = badgeType;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return title;
    }
    // KEEP METHODS END

}
