package com.sharesmile.share;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.sharesmile.share.Title;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TITLE".
*/
public class TitleDao extends AbstractDao<Title, Long> {

    public static final String TABLENAME = "TITLE";

    /**
     * Properties of entity Title.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TitleId = new Property(1, int.class, "titleId", false, "TITLE_ID");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property CategoryId = new Property(3, int.class, "categoryId", false, "CATEGORY_ID");
        public final static Property Category = new Property(4, String.class, "category", false, "CATEGORY");
        public final static Property GoalNStars = new Property(5, int.class, "goalNStars", false, "GOAL_NSTARS");
        public final static Property ImageUrl = new Property(6, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property WinningMessage = new Property(7, String.class, "winningMessage", false, "WINNING_MESSAGE");
        public final static Property Desc = new Property(8, String.class, "desc", false, "DESC");
    };


    public TitleDao(DaoConfig config) {
        super(config);
    }
    
    public TitleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TITLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE_ID\" INTEGER NOT NULL ," + // 1: titleId
                "\"TITLE\" TEXT NOT NULL ," + // 2: title
                "\"CATEGORY_ID\" INTEGER NOT NULL ," + // 3: categoryId
                "\"CATEGORY\" TEXT NOT NULL ," + // 4: category
                "\"GOAL_NSTARS\" INTEGER NOT NULL ," + // 5: goalNStars
                "\"IMAGE_URL\" TEXT," + // 6: imageUrl
                "\"WINNING_MESSAGE\" TEXT NOT NULL ," + // 7: winningMessage
                "\"DESC\" TEXT);"); // 8: desc
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TITLE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Title entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTitleId());
        stmt.bindString(3, entity.getTitle());
        stmt.bindLong(4, entity.getCategoryId());
        stmt.bindString(5, entity.getCategory());
        stmt.bindLong(6, entity.getGoalNStars());
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(7, imageUrl);
        }
        stmt.bindString(8, entity.getWinningMessage());
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(9, desc);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Title readEntity(Cursor cursor, int offset) {
        Title entity = new Title( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // titleId
            cursor.getString(offset + 2), // title
            cursor.getInt(offset + 3), // categoryId
            cursor.getString(offset + 4), // category
            cursor.getInt(offset + 5), // goalNStars
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // imageUrl
            cursor.getString(offset + 7), // winningMessage
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // desc
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Title entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitleId(cursor.getInt(offset + 1));
        entity.setTitle(cursor.getString(offset + 2));
        entity.setCategoryId(cursor.getInt(offset + 3));
        entity.setCategory(cursor.getString(offset + 4));
        entity.setGoalNStars(cursor.getInt(offset + 5));
        entity.setImageUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setWinningMessage(cursor.getString(offset + 7));
        entity.setDesc(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Title entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Title entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
