package com.sharesmile.share;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WORKOUT".
 */
public class Workout {

    private Long id;
    private float distance;
    private float elapsedTime;
    private Integer steps;
    private float recordedTime;
    private float avgSpeed;
    private java.util.Date date;

    public Workout() {
    }

    public Workout(Long id) {
        this.id = id;
    }

    public Workout(Long id, float distance, float elapsedTime, Integer steps, float recordedTime, float avgSpeed, java.util.Date date) {
        this.id = id;
        this.distance = distance;
        this.elapsedTime = elapsedTime;
        this.steps = steps;
        this.recordedTime = recordedTime;
        this.avgSpeed = avgSpeed;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public float getDistance() {
        return distance;
    }

    public void setDistance(float distance) {
        this.distance = distance;
    }

    public float getElapsedTime() {
        return elapsedTime;
    }

    public void setElapsedTime(float elapsedTime) {
        this.elapsedTime = elapsedTime;
    }

    public Integer getSteps() {
        return steps;
    }

    public void setSteps(Integer steps) {
        this.steps = steps;
    }

    public float getRecordedTime() {
        return recordedTime;
    }

    public void setRecordedTime(float recordedTime) {
        this.recordedTime = recordedTime;
    }

    public float getAvgSpeed() {
        return avgSpeed;
    }

    public void setAvgSpeed(float avgSpeed) {
        this.avgSpeed = avgSpeed;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
